config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers, shallow: true
  end

  get '/search', to: 'questions#search', as: 'search'

  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  root to: 'home#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, length: { maximum: 500 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers

  validates :title, length: { minimum: 2 }
  validates :body, length: { maximum: 500 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers

  validates :provider, presence: true
  validates :uid, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, format: { with: /.+@.+\..+/, message: 'incorret email' }

  def self.find_or_create_from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.email = auth.info.email
      user.save!
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :set_question, only: [:index, :new, :create]

  def index
    @answers = @question.answers
  end

  def show; end

  def new
    @answer = Answer.new
  end

  def edit; end

  def create
    @answer = Answer.new(answer_params)
    @answer.question = @question
    @answer.user = current_user

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_answers_path(@answer.question), notice: 'Answer was successfully destroyed.' }
    end
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate
    redirect_to :login unless user_logged_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_logged_in?
    current_user.present?
  end

  def validate_author(object)
    redirect_back(fallback_location: root_path) unless current_user == object.user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:new, :edit, :create, :update, :destroy]
  before_action :validate_question_author, only: [:edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show; end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
    end
  end

  def search
    if params[:search]
      clean_params = params[:search].gsub(/[^0-9A-Za-z]/, '').strip.downcase
      @questions = Question.where('lower(body) LIKE ? OR lower(title) LIKE ?', "%#{clean_params}%", "%#{clean_params}%")
    else
      @questions = Question.all
    end

    respond_to do |format|
      format.html { render :index }
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def validate_question_author
    validate_author(@question)
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_omniauth(request.env['omniauth.auth'])
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def options
    {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: '_blank' },
      space_after_headers: true,
      fenced_code_blocks: true
    }
  end

  def extensions
    {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.slim
= form_for [@question, @answer] do |f|
  - if @answer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      ul
        - @answer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit

app/views/answers/edit.html.slim
h1 Editing answer

== render 'form'

=> link_to 'Show', answer_path(@answer)
'|
=< link_to 'Back', question_answers_path(@answer.question)

app/views/answers/index.html.slim
h1 Listing answers

table
  thead
    tr
      th Body
      th
      th
      th

  tbody
    - @answers.each do |answer|
      tr
        td = markdown(answer.body)
        td = link_to 'Show', answer
        td = link_to 'Edit', edit_answer_path(answer)
        td = link_to 'Destroy', answer, data: { confirm: 'Are you sure?' }, method: :delete

br
div
  = link_to 'New Answer', new_question_answer_path(@question)

div
  = link_to 'Question', question_path(@question)

app/views/answers/new.html.slim
h1 New answer

== render 'form'

= link_to 'Back', question_answers_path(@question)

app/views/answers/show.html.slim
p#notice = notice

p
  strong Body:
  = markdown(@answer.body)
p
  strong Question:
  = @answer.question.title
p
  strong User:
  = @answer.user.first_name

=> link_to 'Edit', edit_answer_path(@answer)
'|
=< link_to 'Back', question_answers_path(@answer.question)

app/views/home/index.html.slim
h1
  |  Welcome
a[href="/auth/google_oauth2"]
  | Sign in with Google


- if current_user
  div
    = "Hi #{current_user.first_name}"
  div
    = link_to 'Logout', :logout

div
  = link_to 'Questions', :questions

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Qanda
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/questions/_form.html.slim
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      h2 = "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      ul
        - @question.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit

app/views/questions/edit.html.slim
h1 Editing question

== render 'form'

=> link_to 'Show', @question
'|
=< link_to 'Back', questions_path

app/views/questions/index.html.slim
h1 Listing questions

table
  thead
    tr
      th Title
      th Body
      th User
      th
      th
      th

  tbody
    - @questions.each do |question|
      tr
        td = question.title
        td = markdown(question.body)
        td = "#{question.user.first_name} #{question.user.last_name}"
        td = link_to 'Show', question
        td = link_to 'Edit', edit_question_path(question)
        td = link_to 'Destroy', question, data: { confirm: 'Are you sure?' }, method: :delete

br

div
  = link_to 'New Question', new_question_path


div
  = form_tag(:search, method: :get) do
    |  Store :
    = text_field_tag :search, params[:search]
    = submit_tag 'Search'

app/views/questions/new.html.slim
h1 New question

== render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.slim
p#notice = notice

p
  strong Title:
  = @question.title
p
  strong Body:
  = markdown(@question.body)
p
  strong User:
  = "#{@question.user.first_name} #{@question.user.last_name}"

div
  = link_to 'Answers', question_answers_path(@question)

div
  => link_to 'Edit', edit_question_path(@question)
  '|
  =< link_to 'Back', questions_path